### ISSUE TITLE
Implicit cv2 dependency

### ISSUE THREAD

**Issue by davedovrat** [halehaka/map_cover#3]
prompt:
ros2 run map_cover predict_node

response:
2023-07-09 07:52:53.145322: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/root/dev_ws/install/map_cover/lib/map_cover/predict_node", line 33, in <module>
    sys.exit(load_entry_point('map-cover==0.0.0', 'console_scripts', 'predict_node')())
  File "/root/dev_ws/install/map_cover/lib/map_cover/predict_node", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/dev_ws/install/map_cover/lib/python3.10/site-packages/map_cover/predict_node.py", line 3, in <module>
    import map_cover.predict, map_cover.map, map_cover.grid
  File "/root/dev_ws/install/map_cover/lib/python3.10/site-packages/map_cover/predict.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by karpase** [comment]
added dependency
