### ISSUE TITLE
Implicit shapely dependency

### ISSUE THREAD

**Issue by davedovrat** [halehaka/map_cover#4]
prompt:
ros2 run mission_planner_srv service

response:
Traceback (most recent call last):
  File "/root/dev_ws/install/mission_planner_srv/lib/mission_planner_srv/service", line 33, in <module>
    sys.exit(load_entry_point('mission-planner-srv==0.0.0', 'console_scripts', 'service')())
  File "/root/dev_ws/install/mission_planner_srv/lib/mission_planner_srv/service", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/dev_ws/install/mission_planner_srv/lib/python3.10/site-packages/mission_planner_srv/mission_planner_srv.py", line 3, in <module>
    from map_cover.grid import *
  File "/root/dev_ws/install/map_cover/lib/python3.10/site-packages/map_cover/grid.py", line 3, in <module>
    import shapely
ModuleNotFoundError: No module named 'shapely'

**Comment by karpase** [comment]
added dependency
